markdown:               kramdown
highlighter:            rouge
permalink:              /:categories/:title.html
relative_permalinks:    false
title:                  'Bits'
tagline:                'Blog posts from @mdminhazulhaque'
description:            'Blog posts from <a href="https://minhazulhaque.com/" target="_blank">@mdminhazulhaque</a>.'
url:                    http://bits.minhazulhaque.com
paginate:               5
exclude:                ['etc', 'CNAME']
author:
    name:               'Md. Minhazul Haque'
    email:              'minhaz@linux.com'
    gplus:              'https://plus.google.com/+MuhammadMinhazulHaque'
    twitter:            'https://twitter.com/mdminhazulhaque'
    github:             'https://github.com/minhazul-haque'
    linkedin:           'https://bd.linkedin.com/in/mdminhazulhaque'
gems:
                        - jekyll-sitemap
                        - jekyll-paginate
